version: "3.9"

services:
  monitor:
    build: ./monitor
    container_name: soc-monitor
    network_mode: "host"
    privileged: true
    restart: always

  alert:
    build: ./alert
    container_name: soc-alert
    ports:
      - "8765:8765"
    restart: always
